<Project>
  <Import Project="$(MSBuildThisFileDirectory)Version.props" />
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <RestoreAdditionalProjectSources>$(RestoreAdditionalProjectSources);$(MSBuildThisFileDirectory).artifacts/control-packages</RestoreAdditionalProjectSources>
  </PropertyGroup>
</Project>
