#!/usr/bin/env python3
"""Generate native Swift paths from the same vector sources used by WPF.

Run explicitly when Windows artwork changes. This is a source generator, not a
renderer: it neither launches the product nor reads installed Codex resources.
"""
from pathlib import Path
import math
import re

ROOT = Path(__file__).resolve().parents[1]
OFFICIAL = ROOT / 'src/CodexMicro.Windows/Services/CodexOfficialArtwork.g.cs'
KEYCAP = ROOT / 'src/CodexMicro.Windows/Controls/KeycapIcon.cs'
OUTPUT = ROOT / 'apps/macos/Sources/CodexMicroMac/MicroArtwork.generated.swift'
NUMBER = r'[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?'


def segments(source):
    tokens = re.findall(r'[A-DF-Za-df-z]|' + NUMBER, source.removeprefix('F1 ').removeprefix('F0 '))
    i, command = 0, None
    x = y = start_x = start_y = 0.0
    count = {'M': 2, 'L': 2, 'H': 1, 'V': 1, 'C': 6, 'Q': 4, 'A': 7}
    while i < len(tokens):
        if tokens[i].isalpha():
            command = tokens[i]
            i += 1
        if command is None:
            raise ValueError('Path without command')
        op, relative = command.upper(), command.islower()
        if op == 'Z':
            yield ('Z', [])
            x, y = start_x, start_y
            command = None
            continue
        if op not in count:
            raise ValueError(f'Unsupported path command: {command}')
        args = list(map(float, tokens[i:i + count[op]]))
        if len(args) != count[op]:
            raise ValueError('Incomplete path')
        i += count[op]
        def point(a, b):
            return (a + x, b + y) if relative else (a, b)
        if op in ['M', 'L']:
            nx, ny = point(*args)
            yield (op, [nx, ny])
            x, y = nx, ny
            if op == 'M':
                start_x, start_y = x, y
                command = 'l' if relative else 'L'
        elif op in ['H', 'V']:
            if op == 'H': x = args[0] + x if relative else args[0]
            else: y = args[0] + y if relative else args[0]
            yield ('L', [x, y])
        elif op in ['C', 'Q']:
            points = [v for j in range(0, len(args), 2) for v in point(*args[j:j + 2])]
            yield (op, points)
            x, y = points[-2:]
        else:
            rx, ry, rotation, large, sweep, end_x, end_y = args
            nx, ny = point(end_x, end_y)
            if (nx, ny) == (x, y):
                continue
            rx, ry = abs(rx), abs(ry)
            if rx == 0 or ry == 0:
                yield ('L', [nx, ny]); x, y = nx, ny; continue
            phi = math.radians(rotation)
            c, s = math.cos(phi), math.sin(phi)
            dx, dy = (x - nx) / 2, (y - ny) / 2
            xp, yp = c * dx + s * dy, -s * dx + c * dy
            radius_scale = max(1, math.sqrt((xp / rx) ** 2 + (yp / ry) ** 2))
            rx, ry = rx * radius_scale, ry * radius_scale
            numerator = max(0, rx * rx * ry * ry - rx * rx * yp * yp - ry * ry * xp * xp)
            denominator = rx * rx * yp * yp + ry * ry * xp * xp
            factor = (1 if large != sweep else -1) * math.sqrt(numerator / denominator)
            cxp, cyp = factor * rx * yp / ry, -factor * ry * xp / rx
            cx, cy = c * cxp - s * cyp + (x + nx) / 2, s * cxp + c * cyp + (y + ny) / 2
            theta = math.atan2((yp - cyp) / ry, (xp - cxp) / rx)
            finish = math.atan2((-yp - cyp) / ry, (-xp - cxp) / rx)
            delta = (finish - theta) % (2 * math.pi)
            if not sweep: delta -= 2 * math.pi
            pieces = max(1, math.ceil(abs(delta) / (math.pi / 2)))
            def at(t):
                return (cx + c * rx * math.cos(t) - s * ry * math.sin(t), cy + s * rx * math.cos(t) + c * ry * math.sin(t))
            def tangent(t):
                return (-c * rx * math.sin(t) - s * ry * math.cos(t), -s * rx * math.sin(t) + c * ry * math.cos(t))
            for piece in range(pieces):
                a, b = theta + delta * piece / pieces, theta + delta * (piece + 1) / pieces
                k = 4 / 3 * math.tan((b - a) / 4)
                p0, p3, d0, d3 = at(a), at(b), tangent(a), tangent(b)
                yield ('C', [p0[0] + k * d0[0], p0[1] + k * d0[1], p3[0] - k * d3[0], p3[1] - k * d3[1], *p3])
            x, y = nx, ny


def main():
    official, local = OFFICIAL.read_text(), KEYCAP.read_text()
    output = ['// Generated by scripts/export-macos-artwork.py. Do not edit paths by hand.', 'import CoreGraphics', '', 'enum MicroArtwork {', '    struct Layer { let evenOdd: Bool; let path: CGPath }', '    private static func path(_ draw: (CGMutablePath) -> Void) -> CGPath { let p = CGMutablePath(); draw(p); return p }', '    private static func stroked(_ width: CGFloat, _ draw: (CGMutablePath) -> Void) -> CGPath { let p = CGMutablePath(); draw(p); return p.copy(strokingWithWidth: width, lineCap: .round, lineJoin: .round, miterLimit: 10) }', '    static let layers: [String: [Layer]] = [']
    # Windows overrides the generic MIND artwork with DrawReasoningSlider.
    # Its native counterpart is ReasoningGlyph; do not import the old brains.
    # BRANCH's exported open paths omit stroke and node circles. KeycapGlyph
    # uses the complete KeycapIcon.DrawBranch geometry instead.
    keys = ['FAST', 'FAST_ON', 'SKETCH'] + sorted(set(re.findall(r'\["([A-Z0-9+_.-]+)"\] = "[^"]+"', official)) - {'FAST', 'MIND+', 'MIND-', 'BRANCH'})
    for key in keys:
        if key == 'FAST':
            definition = re.search(r'PaperFastGeometry\s*=\s*CreateGeometry\((.*?)\);', local, re.S).group(1)
            width, height, scale, offset_x, offset_y = 24, 24, 1, 0, 0
        elif key == 'SKETCH':
            definition = re.search(r'SketchGeometry\s*=\s*CreateGeometry\((.*?)\)\[0\];', local, re.S).group(1)
            width, height, scale, offset_x, offset_y = 20, 20, 1, 0, 0
        elif key == 'UPL':
            # The generic exported cloud paths lose their stroke, hiding the
            # upload arrow. Preserve the complete native fallback geometry.
            definition = re.search(r'private static void DrawCloudUpload\(.*?Geometry.Parse\((.*?)\)', local, re.S).group(1)
            width, height, scale, offset_x, offset_y = 20, 20, 1, 0, 0
        else:
            name = re.search(r'\["' + re.escape('FAST' if key == 'FAST_ON' else key) + r'"\] = "([^"]+)"', official).group(1)
            definition = re.search(r'\["' + re.escape(name) + r'"\] = new\((.*?)\),\n', official, re.S).group(1)
            width, height, scale, offset_x, offset_y = map(float, definition.split('Create(', 1)[0].rstrip(', ').split(','))
        paths = re.findall(r'"([^"]+)"', definition)
        # WPF defaults to EvenOdd; F1 explicitly selects Nonzero. Preserve it:
        # otherwise the hollow Paper FAST glyph becomes a solid lightning bolt.
        maximum = max(width, height)
        def p(x, y):
            x = (x * scale + offset_x + (maximum - width) / 2) / maximum
            y = (y * scale + offset_y + (maximum - height) / 2) / maximum
            return f'CGPoint(x: {x:.8f}, y: {y:.8f})'
        output += [f'        "{key}": [']
        for source in paths:
            even_odd = str(not source.lstrip().startswith('F1 ')).lower()
            constructor = 'stroked(0.0675)' if key in {'SKETCH', 'UPL'} else 'path'
            output += [f'            Layer(evenOdd: {even_odd}, path: {constructor} {{ p in']
            for op, a in segments(source):
                if op == 'M': line = f'p.move(to: {p(*a)})'
                elif op == 'L': line = f'p.addLine(to: {p(*a)})'
                elif op == 'C': line = f'p.addCurve(to: {p(*a[4:6])}, control1: {p(*a[:2])}, control2: {p(*a[2:4])})'
                elif op == 'Q': line = f'p.addQuadCurve(to: {p(*a[2:4])}, control: {p(*a[:2])})'
                else: line = 'p.closeSubpath()'
                output.append('                ' + line)
            output += ['            }),']
        output += ['        ],']
    output += ['    ]', '}', '']
    OUTPUT.write_text('\n'.join(output))
    print(f'Generated {OUTPUT.relative_to(ROOT)} ({len(keys)} glyphs)')

if __name__ == '__main__':
    main()
